services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: molight-ha
    volumes:
      - ./config:/config
      - ./custom_components/molight:/config/custom_components/molight:ro
    ports:
      - "8123:8123"
    privileged: true
    restart: unless-stopped
